import {createHash} from "node:crypto";import type {StructuredKnowledgeBlock} from "@/lib/rag/types";import {normalizeKnowledgeText} from "./query-normalizer";
export interface ExtractedKnowledgeFact{attributeKey:string;rawValue:string;typedValue:string|number|boolean|string[];unit?:string;polarity:"positive"|"negative"|"unknown";qualifiers:Record<string,string>;evidence:{blockId:string;unitType:string;unitIndex:number;text:string};evidenceHash:string;}
function fact(attributeKey:string,rawValue:string,typedValue:ExtractedKnowledgeFact["typedValue"],block:StructuredKnowledgeBlock,unit?:string,polarity:ExtractedKnowledgeFact["polarity"]="positive",qualifiers:Record<string,string>={}):ExtractedKnowledgeFact{const evidence={blockId:block.id,unitType:block.unitType,unitIndex:block.unitIndex,text:block.text};return{attributeKey,rawValue,typedValue,unit,polarity,qualifiers,evidence,evidenceHash:createHash("sha256").update(`${block.id}\0${attributeKey}\0${rawValue}`).digest("hex")};}
function negated(text:string,term:string){return new RegExp(`(?:\\bno\\b|\\bnot\\b|\\bwithout\\b|does not support|unsupported|不支持|不含|无)\\s*(?:[a-z0-9.+/-]+\\s*){0,5}${term}`,"i").test(text);}
export function extractKnowledgeFacts(blocks:readonly StructuredKnowledgeBlock[]):ExtractedKnowledgeFact[]{const results:ExtractedKnowledgeFact[]=[];const documentHasPoe=blocks.some(block=>/\bpoe\b/i.test(block.text));
  const combined:StructuredKnowledgeBlock[]=[];for(const block of blocks){if(!block.bbox)continue;for(const other of blocks){if(!other.bbox||block.id>=other.id||block.unitType!==other.unitType||block.unitIndex!==other.unitIndex)continue;const center=(block.bbox[1]+block.bbox[3])/2,otherCenter=(other.bbox[1]+other.bbox[3])/2;const ordered=[block,other].sort((a,b)=>a.bbox![0]-b.bbox![0]);const gap=ordered[1].bbox![0]-ordered[0].bbox![2];if(Math.abs(center-otherCenter)<=12&&gap>=0&&gap<=180){combined.push({...block,id:`${ordered[0].id}+${ordered[1].id}`,text:ordered.map(item=>item.text).join(" "),bbox:undefined});}}}
  for(const block of [...blocks,...combined]){if(block.quality!=="success")continue;const texts=[block.text,...(block.table?[block.table.headers.join(" "),...block.table.rows.map(row=>row.join(" "))]:[])];for(const source of texts){const text=normalizeKnowledgeText(source);let match;
    for(const candidate of text.matchAll(/\b(\d+)\s*x\s*(?:10\/100(?:\/1000)?\s*mbps\s*)?(?:auto-negotiation\s*)?(?:rj45(?:\s+ethernet)?|ethernet)\s*ports?\b/gi))results.push(fact("ethernet_port_count",candidate[0],Number(candidate[1]),{...block,text:source},"port"));
    if((match=/\b(?:10\/100(?:\/1000)?\s*mbps\s*)?(?:rj45|ethernet)\s*ports?\s*[:|]?\s*(\d+)\b/i.exec(text)))results.push(fact("ethernet_port_count",match[0],Number(match[1]),{...block,text:source},"port"));
    if((match=/\b(\d+)[- ]ports?\s+(?:10\/100(?:\/1000)?\s*mbps\s+)?ethernet\b/i.exec(text)))results.push(fact("ethernet_port_count",match[0],Number(match[1]),{...block,text:source},"port"));
    for(const [key,label] of [["lan_port_count","lan"],["wan_port_count","wan"]] as const)if((match=new RegExp(`\\b(\\d+)\\s*[x]?\\s*${label}\\s*ports?\\b`,`i`).exec(text)))results.push(fact(key,match[0],Number(match[1]),{...block,text:source},"port"));
    if((match=/\b(\d+)[- ]ports?\s+[^\n;]{0,30}\bpoe\+?\b/i.exec(text)))results.push(fact("poe_output_port_count",match[0],Number(match[1]),{...block,text:source},"port"));
    if((match=/\b(?:with\s+)?(\d+)\s*(?:gigabit\s+)?uplink\s*ports?\b/i.exec(text)))results.push(fact("uplink_port_count",match[0],Number(match[1]),{...block,text:source},"port"));
    if((match=/\b(\d+)\s*[x]?\s*sfp\+\s*ports?\b/i.exec(text)))results.push(fact("sfp_plus_port_count",match[0],Number(match[1]),{...block,text:source},"port"));
    if((match=/\b(\d+)\s*[x]?\s*sfp(?!\+)\s*ports?\b/i.exec(text)))results.push(fact("sfp_port_count",match[0],Number(match[1]),{...block,text:source},"port"));
    if((match=/\busb\s*(2\.0|3\.[012])\b/i.exec(text)))results.push(fact("usb_version",match[0],`USB ${match[1]}`,{...block,text:source}));
    if((match=/\b(\d+)\s*[x]?\s*(?:nano-?)?sim\s*(?:slots?)?\b/i.exec(text)))results.push(fact("sim_count",match[0],Number(match[1]),{...block,text:source},"slot"));
    if(/\bpoe\b/i.test(text)&&((match=/\bpoe[^\n]{0,40}?(\d+(?:\.\d+)?)\s*w\s*(?:poe\s*)?(?:budget|maximum|max|output)\b/i.exec(text))||(match=/\b(?:budget|maximum|max|output)\b[^\n\d]{0,30}(\d+(?:\.\d+)?)\s*w\b/i.exec(text))))results.push(fact("poe_power_budget",match[0],Number(match[1]),{...block,text:source},"W"));
    else if(documentHasPoe&&(match=/\bmax(?:imum)?\s+power\s+consumption\s*\(w\)\s*(\d+(?:\.\d+)?)\b/i.exec(text)))results.push(fact("poe_power_budget",match[0],Number(match[1]),{...block,text:source},"W","unknown",{interpretation:"device maximum; PoE budget requires review"}));
    for(const standard of ["802.3af","802.3at","802.3bt"])if(text.includes(standard))results.push(fact("poe_standard",standard,standard,{...block,text:source},undefined,negated(text,standard.replace(".","\\."))?"negative":"positive"));
    if(/\b(?:supports?|support for|with)\s+poe\b|\bpoe\s+(?:support|capability)\b|支持\s*poe/i.test(text))results.push(fact("poe_capability",source.slice(0,200),!negated(text,"poe"),{...block,text:source},undefined,negated(text,"poe")?"negative":"positive"));
    if(/\bpoe[- ]?in(?:put)?\b|poe受电/i.test(text))results.push(fact("poe_input",source.slice(0,200),!negated(text,"poe[- ]?in(?:put)?"),{...block,text:source},undefined,negated(text,"poe[- ]?in(?:put)?")?"negative":"positive"));
    if(/\bpoe[- ]?out(?:put)?\b|poe供电/i.test(text))results.push(fact("poe_output",source.slice(0,200),!negated(text,"poe[- ]?out(?:put)?"),{...block,text:source},undefined,negated(text,"poe[- ]?out(?:put)?")?"negative":"positive"));
    const ethernetSpeeds=new Set<number>();for(const speed of text.matchAll(/\b(10|100|1000)\s*mbps\b|\b(1|2\.5|5|10)\s*gbps\b/gi)){ethernetSpeeds.add(speed[1]?Number(speed[1])/1000:Number(speed[2]));}if(ethernetSpeeds.size&&/ethernet|rj45|ports?|网口/i.test(text))results.push(fact("ethernet_speed",source.slice(0,300),[...ethernetSpeeds].sort((a,b)=>a-b).map(String),{...block,text:source},"Gbps"));
    if((match=/\bwi-?fi\s*(4|5|6e?|7)\b/i.exec(text)))results.push(fact("wifi_generation",match[0],`Wi-Fi ${match[1].toUpperCase()}`,{...block,text:source}));
    const bands=[...text.matchAll(/\b(2\.4|5|6)\s*ghz\b/gi)].map(item=>`${item[1]} GHz`);if(bands.length)results.push(fact("frequency_band",bands.join(", "),[...new Set(bands)],{...block,text:source}));
    if((match=/\b(4g(?:\s+lte)?|5g(?:\s+nr)?)\b/i.exec(text)))results.push(fact("cellular_generation",match[0],match[1].toUpperCase(),{...block,text:source}));
    const vpnRoles=[...text.matchAll(/\bvpn\s+(client|server|passthrough)\b/gi)].map(item=>item[1].toLowerCase());if(vpnRoles.length)results.push(fact("vpn_role",vpnRoles.join(", "),[...new Set(vpnRoles)],{...block,text:source}));
    if((match=/\b(\d+(?:\.\d+)?)\s*[x×]\s*(\d+(?:\.\d+)?)\s*[x×]\s*(\d+(?:\.\d+)?)\s*mm\b/i.exec(text)))results.push(fact("dimensions",match[0],[match[1],match[2],match[3]],{...block,text:source},"mm"));
    if((match=/\b(?:net\s+)?weight\s*[:|]?\s*(\d+(?:\.\d+)?)\s*(kg|g)\b/i.exec(text)))results.push(fact("weight",match[0],Number(match[1])*(match[2].toLowerCase()==="kg"?1000:1),{...block,text:source},"g"));
    if(/\b(?:distributor|reseller|retailer|isp|system integrator)\b|渠道角色|经销商|分销商/i.test(text)&&/\b(?:means|refers to|responsible for|role)\b|是指|负责|定义/i.test(text))results.push(fact("channel_role_definition",source.slice(0,500),source.slice(0,500),{...block,text:source},undefined,"positive"));
    if(/\b(?:must|required|only if|subject to|applies? to)\b|必须|条件|仅当|适用于/i.test(text))results.push(fact("policy_condition",source.slice(0,500),source.slice(0,500),{...block,text:source},undefined,"positive"));
  }}const unique=new Map(results.map(item=>[`${item.attributeKey}:${item.evidenceHash}`,item]));return [...unique.values()];}
