"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import type {FactReviewDecision,GoldSourceCoordinate,KnowledgeFactReviewItem,KnowledgeFactReviewResponse,KnowledgeGoldReviewItem,KnowledgeGoldReviewResponse} from "@/lib/knowledge/review-types";

async function readJson<T>(response:Response):Promise<T>{const body=await response.json() as T&{error?:string};if(!response.ok)throw new Error(body.error??"请求失败");return body;}

export function KnowledgeReviewCenter(){const[open,setOpen]=useState(false);const[tab,setTab]=useState<"facts"|"gold">("facts");
  return <section className={`panel knowledge-review-center ${open?"open":""}`}><div className="review-center-entry"><div><h2>复核中心</h2><p>逐项核对事实证据与 Gold 答案。所有决定保留审核人、时间和版本。</p></div><button className="primary-button" onClick={()=>setOpen(value=>!value)}>{open?"收起复核中心":"进入复核中心"}</button></div>{open&&<><div className="review-tabs" role="tablist" aria-label="知识复核类型"><button role="tab" aria-selected={tab==="facts"} className={tab==="facts"?"active":""} onClick={()=>setTab("facts")}>事实复核</button><button role="tab" aria-selected={tab==="gold"} className={tab==="gold"?"active":""} onClick={()=>setTab("gold")}>Gold 审核</button></div>{tab==="facts"?<FactReviewWorkbench/>:<GoldReviewWorkbench/>}</>}</section>;
}

function FactReviewWorkbench(){const[data,setData]=useState<KnowledgeFactReviewResponse|null>(null);const[selectedId,setSelectedId]=useState("");const[reason,setReason]=useState("");const[query,setQuery]=useState("");const[offset,setOffset]=useState(0);const[loading,setLoading]=useState(false);const[message,setMessage]=useState("");
  const load=useCallback(async()=>{try{const params=new URLSearchParams({offset:String(offset),limit:"25",reason,q:query,status:"open"});const next=await readJson<KnowledgeFactReviewResponse>(await fetch(`/api/knowledge/reviews?${params}`,{cache:"no-store"}));setData(next);setSelectedId(current=>next.items.some(item=>item.reviewId===current)?current:next.items[0]?.reviewId??"");}catch(error){setMessage(error instanceof Error?error.message:"事实复核队列读取失败");}finally{setLoading(false);}},[offset,query,reason]);useEffect(()=>{const controller=new AbortController();const params=new URLSearchParams({offset:String(offset),limit:"25",reason,q:query,status:"open"});fetch(`/api/knowledge/reviews?${params}`,{cache:"no-store",signal:controller.signal}).then(response=>readJson<KnowledgeFactReviewResponse>(response)).then(next=>{setData(next);setSelectedId(current=>next.items.some(item=>item.reviewId===current)?current:next.items[0]?.reviewId??"");setLoading(false);}).catch(error=>{if(!controller.signal.aborted){setMessage(error instanceof Error?error.message:"事实复核队列读取失败");setLoading(false);}});return()=>controller.abort();},[offset,query,reason]);
  const selected=data?.items.find(item=>item.reviewId===selectedId)??null;
  return <div className="review-workbench"><div className="review-queue"><div className="review-filters"><input aria-label="搜索事实复核" value={query} onChange={event=>{setLoading(true);setQuery(event.target.value);setOffset(0);}} placeholder="搜索型号、属性或文档"/><select aria-label="复核原因" value={reason} onChange={event=>{setLoading(true);setReason(event.target.value);setOffset(0);}}><option value="">全部原因</option><option value="conflict">冲突</option><option value="low-confidence">低置信度</option><option value="ocr">OCR</option><option value="layout">布局</option></select></div><div className="review-queue-summary"><strong>{data?.total??0}</strong><span>条待处理</span>{Object.entries(data?.counts??{}).map(([key,value])=><small key={key}>{key} {value}</small>)}</div><div className="review-list" aria-busy={loading}>{data?.items.map(item=><button key={item.reviewId} className={item.reviewId===selectedId?"active":""} onClick={()=>setSelectedId(item.reviewId)}><span className={`review-reason ${item.reason}`}>{item.reason}</span><strong>{item.entityKey}</strong><b>{item.attributeKey}</b><small>{item.rawValue}</small></button>)}{!loading&&!data?.items.length&&<p>当前筛选没有待复核事实。</p>}</div><Pagination offset={offset} limit={25} total={data?.total??0} onChange={value=>{setLoading(true);setOffset(value);}}/></div><div className="review-evidence">{selected?<FactEvidence item={selected}/>:<div className="review-empty">从左侧选择一条事实。</div>}</div><aside className="review-decision">{selected&&<FactDecision key={selected.reviewId} item={selected} loading={loading} onBusy={setLoading} onSaved={async()=>{setMessage("复核决定已保存");await load();}} onError={setMessage}/>} {message&&<p className="review-message" role="status">{message}</p>}</aside></div>;
}

function FactDecision({item,loading,onBusy,onSaved,onError}:{item:KnowledgeFactReviewItem;loading:boolean;onBusy:(value:boolean)=>void;onSaved:()=>Promise<void>;onError:(value:string)=>void}){const[note,setNote]=useState(item.resolutionNote??"");const[correctedRaw,setCorrectedRaw]=useState(item.rawValue);const[correctedValue,setCorrectedValue]=useState(JSON.stringify(item.typedValue));const[correctedUnit,setCorrectedUnit]=useState(item.unit??"");async function decide(decision:FactReviewDecision){let typed:unknown=undefined;if(decision==="correct"){try{typed=JSON.parse(correctedValue);}catch{onError("纠正后的结构化值必须是有效 JSON，例如 8、true 或 [\"4G\",\"5G\"]");return;}}onBusy(true);onError("");try{await readJson(await fetch("/api/knowledge/reviews",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({reviewId:item.reviewId,decision,note,...(decision==="correct"?{correctedValue:typed,correctedRawValue:correctedRaw,correctedUnit:correctedUnit||null}:{})})}));await onSaved();}catch(error){onError(error instanceof Error?error.message:"复核决定未保存");}finally{onBusy(false);}}return <><div><h3>作出决定</h3><p>只有“确认为已验证”和“纠正后确认”会进入事实快路径。</p></div><label>审核备注<textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="记录核对依据或保留原因"/></label><details><summary>纠正结构化值</summary><label>原始显示值<input value={correctedRaw} onChange={event=>setCorrectedRaw(event.target.value)}/></label><label>结构化 JSON<input value={correctedValue} onChange={event=>setCorrectedValue(event.target.value)}/></label><label>单位<input value={correctedUnit} onChange={event=>setCorrectedUnit(event.target.value)}/></label><button disabled={loading} onClick={()=>void decide("correct")}>纠正后确认</button></details><div className="review-actions"><button disabled={loading} className="primary-button" onClick={()=>void decide("verify")}>确认为已验证</button><button disabled={loading} onClick={()=>void decide("retain-candidate")}>保留待复核证据</button><button disabled={loading} className="danger-button" onClick={()=>void decide("reject")}>拒绝此事实</button></div></>}

function FactEvidence({item}:{item:KnowledgeFactReviewItem}){const coordinates=Object.entries(item.sourceLocation??{}).filter(([key])=>key!=="evidenceText");return <><header className="evidence-title"><div><span>{item.documentVersion??"未标注版本"}</span><h3>{item.entityKey} · {item.attributeKey}</h3><p>{item.documentTitle}</p></div><a href={item.assetUrl} target="_blank" rel="noreferrer">打开原件</a></header><blockquote>{item.evidenceText||item.rawValue}</blockquote><dl className="evidence-grid"><div><dt>提取值</dt><dd>{item.rawValue}</dd></div><div><dt>结构化值</dt><dd><code>{JSON.stringify(item.typedValue)}</code></dd></div><div><dt>状态</dt><dd>{item.verificationStatus} / {item.reason}</dd></div><div><dt>来源哈希</dt><dd><code>{item.sourceSha256.slice(0,16)}…</code></dd></div>{coordinates.map(([key,value])=><div key={key}><dt>{key}</dt><dd>{String(value)}</dd></div>)}</dl></>}

function GoldReviewWorkbench(){const[data,setData]=useState<KnowledgeGoldReviewResponse|null>(null);const[selectedId,setSelectedId]=useState("");const[split,setSplit]=useState<"development"|"validation"|"holdout">("development");const[reviewed,setReviewed]=useState<""|"true"|"false">("false");const[offset,setOffset]=useState(0);const[loading,setLoading]=useState(false);const[message,setMessage]=useState("");
  const load=useCallback(async()=>{try{const params=new URLSearchParams({offset:String(offset),limit:"25",split,reviewed});const next=await readJson<KnowledgeGoldReviewResponse>(await fetch(`/api/knowledge/evaluation-reviews?${params}`,{cache:"no-store"}));setData(next);setSelectedId(current=>next.items.some(item=>item.id===current)?current:next.items[0]?.id??"");}catch(error){setMessage(error instanceof Error?error.message:"Gold 队列读取失败");}finally{setLoading(false);}},[offset,reviewed,split]);useEffect(()=>{const controller=new AbortController();const params=new URLSearchParams({offset:String(offset),limit:"25",split,reviewed});fetch(`/api/knowledge/evaluation-reviews?${params}`,{cache:"no-store",signal:controller.signal}).then(response=>readJson<KnowledgeGoldReviewResponse>(response)).then(next=>{setData(next);setSelectedId(current=>next.items.some(item=>item.id===current)?current:next.items[0]?.id??"");setLoading(false);}).catch(error=>{if(!controller.signal.aborted){setMessage(error instanceof Error?error.message:"Gold 队列读取失败");setLoading(false);}});return()=>controller.abort();},[offset,reviewed,split]);const selected=data?.items.find(item=>item.id===selectedId)??null;
  async function unlock(){if(!window.confirm(`确认冻结检索配置 ${data?.retrievalProfileKey} 并仅执行一次 holdout？`))return;setLoading(true);try{await readJson(await fetch("/api/knowledge/evaluation-reviews",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"unlock-holdout",confirmed:true})}));setMessage("Holdout 已解锁；冻结配置哈希已记录");await load();}catch(error){setMessage(error instanceof Error?error.message:"Holdout 未解锁");}finally{setLoading(false);}}
  const preHoldoutComplete=Boolean(data&&data.counts.development.reviewed===data.counts.development.total&&data.counts.validation.reviewed===data.counts.validation.total);
  return <div className="gold-review"><div className="gold-progress"><div>{(["development","validation","holdout"] as const).map(key=><button key={key} disabled={key==="holdout"&&!data?.holdoutUnlocked} className={split===key?"active":""} onClick={()=>{setLoading(true);setSplit(key);setOffset(0);}}><span>{key}</span><strong>{data?.counts[key]?.reviewed??0}/{data?.counts[key]?.total??0}</strong></button>)}</div><p>{data?.reviewed??0}/300 已审核。Holdout {data?.holdoutUnlocked?"已解锁":"保持锁定"}。</p>{preHoldoutComplete&&!data?.holdoutUnlocked&&<button className="primary-button" disabled={loading} onClick={()=>void unlock()}>冻结配置并解锁 holdout</button>}</div><div className="review-filters"><select value={reviewed} onChange={event=>{setLoading(true);setReviewed(event.target.value as typeof reviewed);setOffset(0);}} aria-label="Gold 审核状态"><option value="false">仅未审核</option><option value="true">仅已审核</option><option value="">全部</option></select>{data&&<code title={data.retrievalProfileSha256}>{data.retrievalProfileKey}</code>}</div><div className="review-workbench gold"><div className="review-queue"><div className="review-list" aria-busy={loading}>{data?.items.map(item=><button key={item.id} className={item.id===selectedId?"active":""} disabled={item.locked} onClick={()=>setSelectedId(item.id)}><span>{item.language}</span><strong>{item.id}</strong><small>{item.query}</small>{item.reviewed&&<b>已审核 · r{item.revision}</b>}</button>)}{!loading&&!data?.items.length&&<p>当前筛选没有评测项。</p>}</div><Pagination offset={offset} limit={25} total={data?.total??0} onChange={value=>{setLoading(true);setOffset(value);}}/></div><div className="review-evidence gold-evidence">{selected?<GoldEditor key={`${selected.id}:${selected.revision}`} item={selected} loading={loading} onSaved={async()=>{setMessage("Gold 审核已保存");await load();}} onError={setMessage}/>:<div className="review-empty">选择一条评测问题开始审核。</div>}</div></div>{message&&<p className="review-message" role="status">{message}</p>}</div>;
}

function GoldEditor({item,loading,onSaved,onError}:{item:KnowledgeGoldReviewItem;loading:boolean;onSaved:()=>Promise<void>;onError:(value:string)=>void}){const[answer,setAnswer]=useState(item.expectedAnswer);const[note,setNote]=useState(item.reviewNote);const[sources,setSources]=useState<GoldSourceCoordinate[]>(item.expectedSources);const sourceKeys=useMemo(()=>new Set(sources.map(source=>source.assetSha256)),[sources]);
  function addSource(assetSha256:string,version:string|null){if(sourceKeys.has(assetSha256))return;setSources(current=>[...current,{assetSha256,unitIndex:1,...(version?{version}:{})}]);}
  async function save(){onError("");try{await readJson(await fetch("/api/knowledge/evaluation-reviews",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"save",caseId:item.id,caseSha256:item.caseSha256,expectedAnswer:answer,expectedSources:sources,reviewNote:note})}));await onSaved();}catch(error){onError(error instanceof Error?error.message:"Gold 审核未保存");}}
  return <div className="gold-editor"><header><div><span>{item.split} · {item.expectedAction}</span><h3>{item.query}</h3></div><em>{item.sourceGroup}</em></header><dl><div><dt>预期实体</dt><dd>{item.expectedEntities.join("、")||"无"}</dd></div><div><dt>预期结果</dt><dd>{item.expectedOutcome}</dd></div><div><dt>属性</dt><dd>{item.expectedAttribute??"—"}</dd></div></dl><label>正确答案<textarea value={answer} onChange={event=>setAnswer(event.target.value)} placeholder="填写人工核实后的标准答案；未知、冲突和拒绝原因也应明确写出"/></label><section className="gold-sources"><h4>正确来源坐标</h4>{item.sourceSuggestions.length>0&&<div className="source-suggestions">{item.sourceSuggestions.map(source=><div key={source.assetSha256}><button disabled={sourceKeys.has(source.assetSha256)} onClick={()=>addSource(source.assetSha256,source.version)}><span>{source.title}</span><small>{source.version??"未标版本"}</small></button><a href={source.url} target="_blank" rel="noreferrer">打开原件</a></div>)}</div>}{sources.map((source,index)=><div className="source-coordinate" key={`${source.assetSha256}:${index}`}>{source.assetSha256?<code>{source.assetSha256.slice(0,14)}…</code>:<label>来源 SHA-256<input value={source.assetSha256} onChange={event=>setSources(current=>current.map((item,i)=>i===index?{...item,assetSha256:event.target.value.trim().toLowerCase()}:item))} placeholder="64 位哈希"/></label>}<label>页/slide/sheet<input type="number" min="1" value={source.unitIndex} onChange={event=>setSources(current=>current.map((item,i)=>i===index?{...item,unitIndex:Number(event.target.value)}:item))}/></label><label>表格行<input type="number" min="1" value={source.row??""} onChange={event=>setSources(current=>current.map((item,i)=>i===index?{...item,row:event.target.value?Number(event.target.value):undefined}:item))}/></label><button aria-label="移除来源" onClick={()=>setSources(current=>current.filter((_,i)=>i!==index))}>移除</button></div>)}<button onClick={()=>setSources(current=>[...current,{assetSha256:"",unitIndex:1}])}>手动添加来源</button></section><label>审核备注<textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="记录版本、冲突处理或为什么无需来源"/></label><button className="primary-button" disabled={loading||item.locked||!answer.trim()||sources.some(source=>!/^[0-9a-f]{64}$/.test(source.assetSha256)||source.unitIndex<1)} onClick={()=>void save()}>保存此条 Gold</button></div>;
}

function Pagination({offset,limit,total,onChange}:{offset:number;limit:number;total:number;onChange:(offset:number)=>void}){return <div className="review-pagination"><button disabled={offset===0} onClick={()=>onChange(Math.max(0,offset-limit))}>上一页</button><span>{total?`${offset+1}–${Math.min(total,offset+limit)} / ${total}`:"0 / 0"}</span><button disabled={offset+limit>=total} onClick={()=>onChange(offset+limit)}>下一页</button></div>}
