"use client";
import { useState } from "react";
export function MailCompanyLink({messageId,current,onChanged}:{messageId:string;current?:{companyId?:string;companyName?:string;source?:string};onChanged:()=>void}){
  const [saved,setSaved]=useState(current);
  const [companies,setCompanies]=useState<Array<{id:string;displayName:string;country:string}>>([]);const [company,setCompany]=useState(current?.companyId??"");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);
  async function open(){try{const response=await fetch("/api/workspaces/current",{cache:"no-store"});if(!response.ok)throw new Error();setCompanies((await response.json()).companies);}catch{setNotice("候选库读取失败");}}
  async function save(){setBusy(true);try{const response=await fetch(`/api/mailbox/messages/${messageId}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({companyId:company||null,confirmed:true})});if(!response.ok)throw new Error();setSaved({companyId:company||undefined,companyName:companies.find(item=>item.id===company)?.displayName,source:company?"user-confirmed":"user-rejected"});setNotice("公司关联已保存；后续导入不会覆盖人工选择。");onChanged();}catch{setNotice("保存失败");}finally{setBusy(false);}}
  async function remove(){if(!window.confirm("永久删除此本地导入邮件及其待审候选？已确认知识与远程原邮件均保留。"))return;setBusy(true);try{const response=await fetch(`/api/mailbox/messages/${messageId}`,{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({confirmed:true})});if(!response.ok)throw new Error();onChanged();}catch{setNotice("删除失败，可能正在学习中");}finally{setBusy(false);}}
  return <div><p>关联公司：{saved?.companyName??"未确定 / 待选择"} · {saved?.source??"旧邮件未匹配"}</p><details onToggle={event=>{if(event.currentTarget.open&&!companies.length)void open();}}><summary>修改公司关联</summary><select aria-label="关联候选公司" value={company} onChange={event=>setCompany(event.target.value)}><option value="">不关联任何公司</option>{companies.map(item=><option key={item.id} value={item.id}>{item.displayName} · {item.country}</option>)}</select><button disabled={busy} onClick={()=>void save()}>确认保存</button></details><button disabled={busy} onClick={()=>void remove()}>删除此本地邮件（保留知识）</button>{notice&&<p role="status">{notice}</p>}</div>;
}
