"use client";
import {useEffect,useState} from 'react';
import {WorkspaceDialog} from './workspace-dialog';
type Customer={id:string;name:string;domain:string;country:string|null;customer_type:string|null;notes:string;confirmed:boolean;archived:boolean;revision:number;last_contact?:string};
type Event={id:string;time:string|null;subject:string;excerpt:string;thread:string|null;threadEvidence:string;sender:{address:string}[];recipients:{address:string;role?:string}[];source:string;summary:null|{important:boolean;kind:string;summary:string;quote:string;companyName:string;country:string}};
const types:Record<string,string>={partner:'已合作客户',inquiry:'询盘客户',negotiating:'在谈客户'};
const countryName=(value:string)=>value==='unknown'?'国家待确认':new Intl.DisplayNames(['zh'],{type:'region'}).of(value)||value;
export function MailboxCustomers(){
 const [items,setItems]=useState<Customer[]>([]),[countries,setCountries]=useState<{country:string;count:number}[]>([]),[country,setCountry]=useState(''),[offset,setOffset]=useState(0),[more,setMore]=useState(false),[archived,setArchived]=useState(false);
 const [customer,setCustomer]=useState<Customer|null>(null),[events,setEvents]=useState<Event[]>([]),[eventOffset,setEventOffset]=useState(0),[eventMore,setEventMore]=useState(false),[important,setImportant]=useState(false);
 const [revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[edit,setEdit]=useState<Customer|null>(null),[remove,setRemove]=useState(false),[original,setOriginal]=useState<string|null>(null);
 const [mergeTargets,setMergeTargets]=useState<Customer[]>([]),[mergeTarget,setMergeTarget]=useState('');
 async function post(body:unknown){const response=await fetch('/api/mailbox/customers',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'操作失败');return data;}
 async function perform(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn();setRevision(v=>v+1);}catch(e){setError(e instanceof Error?e.message:'操作失败');}finally{setBusy(false);}}
 useEffect(()=>{const controller=new AbortController();fetch(`/api/mailbox/customers?country=${country}&offset=${offset}&archived=${archived}`,{signal:controller.signal,cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error('客户列表读取失败');return r.json();}).then(data=>{setItems(data.items);setMore(data.hasMore);setCountries(data.countries);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[country,offset,archived,revision]);
 const id=customer?.id;
 useEffect(()=>{if(!id)return;const controller=new AbortController();fetch(`/api/mailbox/customers?id=${id}&offset=${eventOffset}`,{signal:controller.signal,cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error('时间线读取失败');return r.json();}).then(data=>{setCustomer(data.customer);setEvents(data.events);setEventMore(data.hasMore);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[id,eventOffset,revision]);
 async function discover(){await perform(async()=>{let next=0;for(;;){const data=await post({action:'discover',offset:next});next=data.nextOffset;setNotice(`已检查 ${next} 封本地邮件`);if(!data.hasMore)break;}setNotice('公司候选已整理，请确认公司名称、国家和归属。');});}
 async function save(value:Customer){await post({action:'save',customer:{id:value.id,revision:value.revision,name:value.name,country:value.country,customer_type:value.customer_type,notes:value.notes,confirmed:value.confirmed,archived:value.archived}});setEdit(null);setRemove(false);}
 return <div className="customer-workspace"><header className="mailbox-actionbar"><label>国家 <select value={country} onChange={e=>{setCountry(e.target.value);setOffset(0);}}><option value="">全部国家</option>{countries.map(item=><option key={item.country} value={item.country}>{countryName(item.country)} ({item.count})</option>)}</select></label><label><input type="checkbox" checked={archived} onChange={e=>{setArchived(e.target.checked);setOffset(0);setCustomer(null);}}/> 查看已移除公司</label><button disabled={busy} onClick={()=>void discover()}>{busy?'正在处理…':'从本地邮件发现公司'}</button><button onClick={()=>setRevision(v=>v+1)}>刷新</button></header>
 {error&&<p role="alert" className="workspace-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <div className="customer-columns"><aside className="customer-list">{items.map(item=><button key={item.id} className={id===item.id?'selected':''} onClick={()=>{setCustomer(item);setEvents([]);setEventOffset(0);}}><strong>{item.name}</strong><span>{countryName(item.country??'unknown')} · {types[item.customer_type??'']??'类型待选择'}</span><small>{item.confirmed?'已确认':'归属待确认'}{item.last_contact?` · ${new Date(item.last_contact).toLocaleDateString()}`:''}</small></button>)}{!items.length&&<p>暂无公司。同步邮件后，点击“从本地邮件发现公司”。</p>}<nav><button disabled={!offset} onClick={()=>setOffset(v=>v-20)}>上一页公司</button><span>{offset/20+1}</span><button disabled={!more} onClick={()=>setOffset(v=>v+20)}>下一页公司</button></nav></aside>
 <section className="customer-timeline" aria-label="客户沟通时间线">{customer?<><header><h3>{customer.name}</h3><p>{customer.domain} · {countryName(customer.country??'unknown')}</p><div className="mailbox-actions"><button disabled={busy} onClick={()=>{setEdit({...customer});setError('');}}>确认 / 编辑 / 备注</button><button disabled={busy||customer.archived} onClick={()=>void perform(async()=>{const data=await post({action:'summarize',id:customer.id});setNotice(`已排队 ${data.queued} 封，本地模型整理后点击刷新查看；不会发送到云模型。`);})}>本地整理重要节点</button><button disabled={busy} onClick={()=>customer.archived?void perform(()=>save({...customer,archived:false})):setRemove(true)}>{customer.archived?'恢复公司':'移除公司'}</button></div><p>备注：{customer.notes||'暂无。备注会作为该公司 Agent 上下文。'}</p><label><input type="checkbox" checked={important} onChange={e=>setImportant(e.target.checked)}/> 本页只看重要节点</label><p className="subtle">仅包含本账号已导入邮件；摘要为内部推断，点击原邮件核对。线程标签标明邮件头或推断依据。</p></header>
 <ol>{events.filter(event=>!important||event.summary?.important).map(event=><li key={event.id}><time>{event.time?new Date(event.time).toLocaleString():'时间未知'}</time><h4>{event.subject||'无主题'}</h4><p>{event.summary?.summary||event.excerpt}</p>{event.summary?.quote&&<blockquote>{event.summary.quote}</blockquote>}{(event.summary?.companyName||event.summary?.country)&&<small>内容推断待确认：{event.summary.companyName} {event.summary.country}</small>}<p>发件：{event.sender.map(p=>p.address).join(', ')}<br/>收件 / 抄送：{event.recipients.map(p=>`${p.address}${p.role?` (${p.role})`:''}`).join(', ')}</p><small>讨论 {event.thread?.slice(0,12)||'独立邮件'} · {event.threadEvidence==='headers'?'邮件头关联':'推断关联'}</small><div className="mailbox-actions"><button onClick={()=>void perform(async()=>{const r=await fetch(`/api/mailbox/messages/${event.id}`);const data=await r.json();if(!r.ok)throw new Error(data.error);setOriginal(data.message.bodyText);})}>查看原邮件</button>{event.source!=='confirmed'&&<button disabled={busy} onClick={()=>void perform(async()=>{await post({action:'link',id:customer.id,messageId:event.id,source:'confirmed'});})}>确认属于此公司</button>}<button disabled={busy} onClick={()=>void perform(async()=>{await post({action:'link',id:customer.id,messageId:event.id,source:'rejected'});})}>排除此邮件</button></div></li>)}</ol>{!events.length&&<p>当前页没有往来记录。</p>}<nav><button disabled={!eventOffset} onClick={()=>setEventOffset(v=>v-20)}>较新往来</button><span>第 {eventOffset/20+1} 页</span><button disabled={!eventMore} onClick={()=>setEventOffset(v=>v+20)}>更早往来</button></nav></>:<p>选择公司查看统一时间线</p>}</section></div>
 {edit&&<WorkspaceDialog title="客户信息与 Agent 备注" busy={busy} onClose={()=>setEdit(null)}><form className="customer-edit" onSubmit={e=>{e.preventDefault();void perform(()=>save(edit));}}><label>公司名称<input required value={edit.name} maxLength={200} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label>国家代码（如 DE，未知留空）<input pattern="[A-Z]{2}" maxLength={2} value={edit.country??''} onChange={e=>setEdit({...edit,country:e.target.value.toUpperCase()||null})}/></label><label>客户类型<select value={edit.customer_type??''} onChange={e=>setEdit({...edit,customer_type:e.target.value||null})}><option value="">待选择</option>{Object.entries(types).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>备注<textarea rows={6} maxLength={8000} value={edit.notes} onChange={e=>setEdit({...edit,notes:e.target.value})}/></label><details onToggle={event=>{if(event.currentTarget.open)void perform(async()=>{const all:Customer[]=[];for(let at=0;;at+=20){const r=await fetch(`/api/mailbox/customers?offset=${at}`);if(!r.ok)throw new Error('Cannot load companies');const data=await r.json();all.push(...data.items);if(!data.hasMore)break;}setMergeTargets(all);});}}><summary>合并到另一家公司</summary><p>将本公司往来并入目标时间线，本记录移入已移除公司；原备注保留在原记录中。合并前请先保存当前编辑。</p><select aria-label="合并目标" value={mergeTarget} onChange={e=>setMergeTarget(e.target.value)}><option value="">选择目标公司</option>{mergeTargets.filter(c=>c.id!==edit.id).map(c=><option key={c.id} value={c.id}>{c.name} ({c.domain})</option>)}</select><button type="button" disabled={busy||!mergeTarget} onClick={()=>void perform(async()=>{await post({action:'merge',id:edit.id,targetId:mergeTarget});setCustomer(mergeTargets.find(c=>c.id===mergeTarget)??null);setEdit(null);setEventOffset(0);setMergeTarget('');})}>确认合并</button></details><label><input type="checkbox" checked={edit.confirmed} onChange={e=>setEdit({...edit,confirmed:e.target.checked})}/> 已核对公司身份与国家</label>{error&&<p role="alert">{error}</p>}<button className="primary-button" disabled={busy}>保存</button></form></WorkspaceDialog>}
 {remove&&customer&&<WorkspaceDialog title="移除客户公司" busy={busy} onClose={()=>setRemove(false)}><p>将“{customer.name}”移出客户列表？之后可在已移除公司中恢复，原始邮箱邮件保留。</p>{error&&<p role="alert">{error}</p>}<footer className="workspace-dialog-actions"><button disabled={busy} onClick={()=>setRemove(false)}>取消</button><button disabled={busy} className="destructive-button" onClick={()=>void perform(()=>save({...customer,archived:true}))}>移除公司</button></footer></WorkspaceDialog>}
 {original!==null&&<WorkspaceDialog title="原邮件正文" onClose={()=>setOriginal(null)}><pre className="mail-original-text">{original}</pre></WorkspaceDialog>}
 </div>;
}
