"use client";
import {useEffect,useState} from 'react';
type Mail={id:string;subject:string;bodyText:string;sentAt?:string;sender:{address:string}[];recipients:{address:string;role?:string}[]};
export function MailboxReader({direction}:{direction:'inbound'|'outbound'}){
 const [offset,setOffset]=useState(0),[items,setItems]=useState<Mail[]>([]),[more,setMore]=useState(false),[id,setId]=useState(''),[mail,setMail]=useState<Mail|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0),[loading,setLoading]=useState(true);
 useEffect(()=>{const controller=new AbortController();fetch(`/api/mailbox/messages?direction=${direction}&offset=${offset}`,{signal:controller.signal,cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error('邮件列表读取失败');return r.json();}).then(data=>{setItems(data.messages);setMore(data.hasMore);setError('');setLoading(false);}).catch(e=>{if(!controller.signal.aborted){setError(e.message);setLoading(false);}});return()=>controller.abort();},[direction,offset,revision]);
 useEffect(()=>{if(!id)return;const controller=new AbortController();fetch(`/api/mailbox/messages/${id}`,{signal:controller.signal,cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error('邮件原文读取失败');return r.json();}).then(data=>{setMail(data.message);setError('');}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[id,revision]);
 return <div className={`mail-reader ${id?"has-selection":""}`}><aside><div className="mailbox-actionbar"><span>本页 {items.length} 封</span><button onClick={()=>setRevision(v=>v+1)}>刷新</button></div>{error&&<p role="alert" className="workspace-error">{error}</p>}
 <div className="mail-reader-list">{items.map(item=><button key={item.id} className={id===item.id?'selected':''} onClick={()=>{setId(item.id);setMail(null);setError('');}}><strong>{item.subject||'无主题'}</strong><small>{item.sender.map(p=>p.address).join(', ')} · {item.sentAt?new Date(item.sentAt).toLocaleString():'时间未知'}</small><span>{item.bodyText}</span></button>)}{!items.length&&<p>{loading?'正在读取…':'没有已同步邮件。使用“管理 / 连接邮箱”同步近期收件和已发送。'}</p>}</div>
 <nav><button disabled={!offset} onClick={()=>{setOffset(v=>v-20);setLoading(true);}}>上一页</button><span>第 {offset/20+1} 页</span><button disabled={!more} onClick={()=>{setOffset(v=>v+20);setLoading(true);}}>下一页</button></nav></aside>
 <section className="mail-reader-body" aria-label="邮件阅读区"><button className="mail-reader-back" onClick={()=>{setId('');setMail(null);}}>返回邮件列表</button>{error&&<p role="alert">{error}</p>}{mail?<><h3>{mail.subject||'无主题'}</h3><p>发件：{mail.sender.map(p=>p.address).join(', ')}</p><p>收件 / 抄送：{mail.recipients.map(p=>`${p.address}${p.role?` (${p.role})`:''}`).join(', ')}</p><p>{mail.sentAt?new Date(mail.sentAt).toLocaleString():'时间未知'}</p><pre>{mail.bodyText}</pre></>:<p>{id?'正在读取原文…':'选择一封邮件阅读'}</p>}</section></div>;
}
