function object(value:unknown):Record<string,unknown>{return value!==null&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};}
function text(value:unknown):string{return value===null||value===undefined?"未记录":typeof value==="boolean"?(value?"是":"否"):typeof value==="string"||typeof value==="number"?String(value):"展开技术记录查看";}
const labels:Record<string,string>={market_country_code:"国家（未记录即未确认）",company:"公司",stage:"环节",status:"状态",revision:"草稿版本",model:"模型",prompt_version:"提示版本",created_at:"创建时间",updated_at:"更新时间",sent_at:"发送时间",started_at:"开始时间",finished_at:"结束时间",target_count:"目标数量",processed_count:"已处理数量",search_credits_used:"搜索额度",extract_credits_used:"提取额度",error_code:"发送状态码"};
const metrics:Record<string,string>={inputItems:"输入条目",outputItems:"输出条目",validOutputItems:"有效输出",downstreamUsedItems:"下游使用输出",inputTokens:"输入 token",outputTokens:"输出 token",promptTokens:"输入 token",completionTokens:"输出 token",latencyMs:"耗时（毫秒）",retries:"重试次数",costUsd:"已报告费用（美元）",accountCashCostUsd:"已报告费用（美元）",usageBoundary:"使用统计边界"};
export function TaskRecordSummary({details}:{details:Record<string,unknown>}){
  const usage=object(details.metrics??details.generation_metrics);const candidates=Array.isArray(details.candidates)?details.candidates.map(object):[];const contacts=Array.isArray(details.items)?details.items.map(object):[];
  return <section><dl>{Object.entries(labels).filter(([key])=>key in details).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{text(details[key])}</dd></div>)}</dl>
    {Object.keys(usage).length>0&&<><h3>本环节用量</h3><dl>{Object.entries(metrics).filter(([key])=>key in usage).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{text(usage[key])}</dd></div>)}</dl><p>未记录不等于零；保存、批准、发送和投递是不同的使用边界。</p></>}
    {candidates.length>0&&<div className="table-scroll"><table className="data-table"><thead><tr><th>公司</th><th>主角色</th><th>评分</th><th>合格</th><th>入库</th><th>理由 / 风险</th></tr></thead><tbody>{candidates.map((item,index)=><tr key={index}><td>{text(item.company)}</td><td>{text(item.role)}</td><td>{text(item.score)}</td><td>{text(item.eligible)}</td><td>{text(item.selected)}</td><td>{[...(Array.isArray(item.reasons)?item.reasons:[]),...(Array.isArray(item.risks)?item.risks:[])].map(text).join("；")||"未记录"}</td></tr>)}</tbody></table></div>}
    {contacts.map((item,index)=><article key={index}><h3>{text(item.company)}</h3><p>状态：{text(item.status)} · 阶段：{text(item.phase)} · 尝试：{text(item.attempts)}</p><p>联系人 {text(item.named_contact_count)} · 邮箱 {text(item.email_count)} · 搜索额度 {text(item.search_credits_used)} · 提取额度 {text(item.extract_credits_used)}</p>{item.error_message?<p role="status">{text(item.error_message)}</p>:null}</article>)}
    {typeof (details.body??details.bodyText)==="string"&&<details><summary>草稿 / 邮件正文</summary><pre style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere"}}>{text(details.body??details.bodyText)}</pre></details>}
  </section>;
}
