import nextEnv from "@next/env";
import { OWNER_USER_ID } from "../src/lib/auth/config";
import { extractKnowledgeFacts } from "../src/lib/knowledge/fact-extractor";
import { getPool, tenantQuery, tenantTransaction } from "../src/lib/rag/db";
import type { StructuredKnowledgeBlock } from "../src/lib/rag/types";

nextEnv.loadEnvConfig(process.cwd());
const write=process.argv.includes("--write");
const releaseKey=process.argv.find(value=>value.startsWith("--release="))?.slice(10)??"rag-v3-shadow-2026-09-18";
type Row={releaseId:string;chunkId:string;documentId:string;sourceRevisionId:string;sourceUnitId:string|null;assetId:string;documentVersion:string|null;market:string|null;sourceNature:string;chunkEntityCount:number;entityId:string;entityType:string;entityVersion:string|null;bindingMethod:string;content:string;blockType:StructuredKnowledgeBlock["blockType"];headingPath:string[];sourceLocation:Record<string,unknown>;metadata:{evidenceStatus?:string};};
const rows=await tenantQuery<Row>(OWNER_USER_ID,`select r.id as "releaseId",c.id as "chunkId",c.document_id as "documentId",c.source_revision_id as "sourceRevisionId",c.source_unit_id as "sourceUnitId",a.id as "assetId",a.document_version as "documentVersion",a.market,a.source_nature as "sourceNature",count(*) over(partition by c.id)::int as "chunkEntityCount",e.id as "entityId",e.entity_type as "entityType",a.document_version as "entityVersion",ce.binding_method as "bindingMethod",c.content,c.block_type as "blockType",c.heading_path as "headingPath",c.source_location as "sourceLocation",c.metadata from knowledge_release_v3 r join knowledge_chunk_v3 c on c.release_id=r.id join knowledge_source_revision_v3 sr on sr.id=c.source_revision_id join knowledge_asset a on a.id=sr.asset_id join knowledge_chunk_entity_v3 ce on ce.chunk_id=c.id join knowledge_entity e on e.id=ce.entity_id where r.release_key=$1 and r.status='building' order by c.id,e.id`,[releaseKey],"admin");
if(!rows.length)throw new Error("Building release has no entity-bound chunks");

type Planned={row:Row;fact:ReturnType<typeof extractKnowledgeFacts>[number];status:"candidate"|"verified"};
const planned:Planned[]=[];const byAttribute:Record<string,number>={};
for(const row of rows){const location=row.sourceLocation;const block:StructuredKnowledgeBlock={id:row.chunkId,assetId:row.assetId,unitType:(location.unitType as StructuredKnowledgeBlock["unitType"])??"document",unitIndex:Number(location.unitIndex??1),blockType:row.blockType,text:row.content,headingPath:row.headingPath,extractorVersion:"docling-v3.0.3",quality:"success"};
  for(const fact of extractKnowledgeFacts([block])){const exactEntityBinding=row.bindingMethod==="xlsx-model-cell-exact-normalized"||row.chunkEntityCount===1;const controlled=/^(?:public-|official-|product-catalog-category$)/.test(row.sourceNature);const parsed=row.metadata.evidenceStatus!=="candidate";const direct=!fact.evidence.blockId.includes("+");const status=fact.polarity!=="unknown"&&controlled&&parsed&&direct&&exactEntityBinding?"verified":"candidate";planned.push({row,fact,status});byAttribute[fact.attributeKey]=(byAttribute[fact.attributeKey]??0)+1;}}
const duplicateKeys=new Set<string>();const values=new Map<string,Set<string>>();for(const item of planned.filter(item=>item.status==="verified")){const key=`${item.row.entityId}:${item.fact.attributeKey}`;const set=values.get(key)??new Set<string>();set.add(`${JSON.stringify(item.fact.typedValue)}:${item.fact.polarity}`);values.set(key,set);if(set.size>1)duplicateKeys.add(key);}
const counts={verified:0,candidate:0,conflicting:0};for(const item of planned){const finalStatus=duplicateKeys.has(`${item.row.entityId}:${item.fact.attributeKey}`)?"conflicting":item.status;counts[finalStatus]++;}
const report={mode:write?"shadow-write":"dry-run-read-only",releaseKey,chunks:new Set(rows.map(row=>row.chunkId)).size,entityChunkBindings:rows.length,extractedFacts:planned.length,counts,byAttribute,modelCalls:0,embeddingCalls:0,externalCalls:0};
if(!write){console.log(JSON.stringify(report,null,2));await getPool().end();process.exit(0);}
const releaseId=rows[0].releaseId;
await tenantTransaction(OWNER_USER_ID,async client=>{
  const state=await client.query<{status:string}>(`select status from knowledge_release_v3 where id=$1 for update`,[releaseId]);if(state.rows[0]?.status!=="building")throw new Error("Facts may only be rebuilt inside a building release");
  await client.query(`delete from knowledge_fact_v3 where release_id=$1`,[releaseId]);
  for(const item of planned){const {row,fact}=item;const status=duplicateKeys.has(`${row.entityId}:${fact.attributeKey}`)?"conflicting":item.status;const location:Record<string,unknown>={...row.sourceLocation,chunkId:row.chunkId,evidenceText:fact.evidence.text.slice(0,1000)};const tableCoordinate=location.rowStart?{sheetName:location.sheetName??null,rowStart:location.rowStart,rowEnd:location.rowEnd??location.rowStart}:null;
    const inserted=await client.query<{id:string}>(`insert into knowledge_fact_v3(release_id,source_revision_id,chunk_id,entity_id,entity_version,market,attribute_key,raw_field_name,typed_value,raw_value,unit,qualifiers,polarity,table_coordinate,evidence_location,evidence_hash,validation_rule,validation_rule_version,verification_status,verified_at) values($1,$2,$3,$4,$5,$6,$7,$7,$8::jsonb,$9,$10,$11::jsonb,$12,$13::jsonb,$14::jsonb,$15,'deterministic-docling-v3','attribute-registry-v1.2.1',$16,$17) on conflict(release_id,entity_id,attribute_key,evidence_hash) do update set typed_value=excluded.typed_value,raw_value=excluded.raw_value,unit=excluded.unit,qualifiers=excluded.qualifiers,polarity=excluded.polarity,table_coordinate=excluded.table_coordinate,evidence_location=excluded.evidence_location,verification_status=excluded.verification_status,verified_at=excluded.verified_at returning id`,[releaseId,row.sourceRevisionId,row.chunkId,row.entityId,row.entityVersion,row.market,fact.attributeKey,JSON.stringify(fact.typedValue),fact.rawValue,fact.unit??null,JSON.stringify(fact.qualifiers),fact.polarity,JSON.stringify(tableCoordinate),JSON.stringify(location),fact.evidenceHash,status,status==="verified"?new Date().toISOString():null]);
    if(status==="candidate"&&row.metadata.evidenceStatus!=="candidate")await client.query(`insert into knowledge_review_queue_v3(release_id,asset_id,fact_id,reason,status) select $1,$2,$3,'low-confidence','open' where not exists(select 1 from knowledge_review_queue_v3 where release_id=$1 and fact_id=$3)`,[releaseId,row.assetId,inserted.rows[0].id]);
    if(status==="conflicting")await client.query(`insert into knowledge_review_queue_v3(release_id,asset_id,fact_id,reason,status) select $1,$2,$3,'conflict','open' where not exists(select 1 from knowledge_review_queue_v3 where release_id=$1 and fact_id=$3)`,[releaseId,row.assetId,inserted.rows[0].id]);
  }
  await client.query(`update knowledge_release_asset_v3 m set verified_facts=s.verified,candidate_facts=s.candidate,conflict_facts=s.conflicting,updated_at=now() from(select sr.asset_id,count(*) filter(where f.verification_status='verified')::int verified,count(*) filter(where f.verification_status='candidate')::int candidate,count(*) filter(where f.verification_status='conflicting')::int conflicting from knowledge_source_revision_v3 sr left join knowledge_fact_v3 f on f.source_revision_id=sr.id where sr.release_id=$1 group by sr.asset_id)s where m.release_id=$1 and m.asset_id=s.asset_id`,[releaseId]);
},"admin");
console.log(JSON.stringify({...report,releaseId,status:"building-not-active"},null,2));await getPool().end();
