import {createHash} from "node:crypto";import {readFile} from "node:fs/promises";import nextEnv from "@next/env";
import {OWNER_USER_ID} from "../src/lib/auth/config";import {getPool,tenantQuery,tenantTransaction} from "../src/lib/rag/db";import {chunkDocumentV2} from "../src/lib/rag/chunker";import type {StructuredKnowledgeBlock} from "../src/lib/rag/types";
nextEnv.loadEnvConfig(process.cwd());
const artifactPath="tmp/knowledge-shadow-v2.json";const payload=JSON.parse(await readFile(artifactPath,"utf8")) as {extractorVersion:string;documents:Array<{storageKey:string;sourceSha256:string;qualitySummary:Record<string,number>;blocks:StructuredKnowledgeBlock[]}>};
const generations=await tenantQuery<{id:string}>(OWNER_USER_ID,`insert into knowledge_index_generation(name,status,extractor_version) values($1,'building',$2) on conflict(name) do update set extractor_version=excluded.extractor_version returning id`,["shadow-layout-v2-2026-09-17",payload.extractorVersion],"admin");const generationId=generations[0].id;let documents=0,chunks=0;const reusedVectors=0;
for(const document of payload.documents){const assets=await tenantQuery<{assetId:string;documentId:string}>(OWNER_USER_ID,`select a.id as "assetId",a.document_id as "documentId" from knowledge_asset a join knowledge_document d on d.id=a.document_id where a.storage_key=$1 and a.source_sha256=$2 and(d.visibility='shared' or d.owner_id=$3)`,[document.storageKey,document.sourceSha256,OWNER_USER_ID],"admin");
  for(const asset of assets){const artifactSha=createHash("sha256").update(JSON.stringify(document)).digest("hex");const revisions=await tenantQuery<{id:string}>(OWNER_USER_ID,`insert into knowledge_source_revision(asset_id,generation_id,source_sha256,extractor_version,artifact_sha256,quality_summary) values($1,$2,$3,$4,$5,$6) on conflict(asset_id,generation_id,source_sha256,extractor_version) do update set artifact_sha256=excluded.artifact_sha256,quality_summary=excluded.quality_summary returning id`,[asset.assetId,generationId,document.sourceSha256,payload.extractorVersion,artifactSha,JSON.stringify(document.qualitySummary)],"admin");const built=chunkDocumentV2(document.blocks,{maxTokens:500});
    await tenantTransaction(OWNER_USER_ID,async client=>{for(const chunk of built){await client.query(`insert into knowledge_chunk_v2(document_id,source_revision_id,generation_id,chunk_index,parent_key,block_type,source_location,heading_path,content,normalized_text,token_estimate,content_sha256,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) on conflict(document_id,generation_id,chunk_index) do update set source_revision_id=excluded.source_revision_id,parent_key=excluded.parent_key,block_type=excluded.block_type,source_location=excluded.source_location,heading_path=excluded.heading_path,content=excluded.content,normalized_text=excluded.normalized_text,token_estimate=excluded.token_estimate,content_sha256=excluded.content_sha256,metadata=excluded.metadata`,[asset.documentId,revisions[0].id,generationId,chunk.index,chunk.parentKey,chunk.blockType,JSON.stringify(chunk.sourceLocation),chunk.headingPath,chunk.content,chunk.normalizedText??null,chunk.tokenEstimate,chunk.contentSha256,JSON.stringify({embeddingStatus:"not-requested"})]);} },"admin");documents++;chunks+=built.length;}
}
await tenantQuery(OWNER_USER_ID,"update knowledge_index_generation set status='validated' where id=$1 and status='building'",[generationId],"admin");console.log(JSON.stringify({mode:"shadow",generationId,status:"validated-not-active",documents,chunks,reusedVectors,embeddingCalls:0,modelCalls:0,externalCalls:0},null,2));await getPool().end();
