/* eslint-disable @typescript-eslint/no-explicit-any -- controlled manifest shapes are validated by the extraction stage */
import {createHash} from "node:crypto";import {readFile,readdir,stat} from "node:fs/promises";import {resolve,relative} from "node:path";import nextEnv from "@next/env";
import {OWNER_USER_ID} from "../src/lib/auth/config";import {getPool,tenantQuery} from "../src/lib/rag/db";import {registerKnowledgeAsset} from "../src/lib/knowledge/document-repository";import {linkKnowledgeDocumentEntities} from "../src/lib/knowledge/entity-resolver";
nextEnv.loadEnvConfig(process.cwd());
type Entry={externalId:string;sourceFile:string;sourceType:string;language?:string;title:string;version?:string;entities:Array<{type:"product"|"company"|"industry-topic";key:string;name?:string}>};
const product=JSON.parse(await readFile(resolve("knowledge/product/processed/product-catalog.json"),"utf8"));const company=JSON.parse(await readFile(resolve("knowledge/company/processed/company-manifest.json"),"utf8"));const industry=JSON.parse(await readFile(resolve("knowledge/industry/processed/industry-manifest.json"),"utf8"));
const external=(d:any)=>{const identity=d.sourceType==="product-catalog-category"?`${d.sourceFile}:${d.knowledgeFile}`:d.sourceFile;return `product:${d.sourceType}:${createHash("sha256").update(`${d.sourceType}:${identity}`).digest("hex").slice(0,24)}`;};
const entries:Entry[]=[...product.datasheets.filter((d:any)=>d.knowledgeFile).map((d:any)=>({externalId:external({...d,sourceType:"public-product-datasheet"}),sourceFile:`knowledge/product/${d.sourceFile}`,sourceType:"public-product-datasheet",language:"en",title:d.title??`${(d.relatedModels??[d.model]).join(" / ")} Datasheet`,version:d.datasheetVersion,entities:(d.relatedModels??[d.model]).map((key:string)=>({type:"product" as const,key}))})),...product.catalogDocuments.map((d:any)=>({externalId:external(d),sourceFile:`knowledge/product/${d.sourceFile}`,sourceType:d.sourceType,language:"en",title:d.title,entities:(d.relatedModels??[]).map((key:string)=>({type:"product" as const,key}))})),...product.references.map((d:any)=>({externalId:external(d),sourceFile:`knowledge/product/${d.sourceFile}`,sourceType:d.sourceType,language:/[\u3400-\u9fff]/.test(d.title)?"zh-CN":"en",title:d.title,entities:(d.relatedModels??[]).map((key:string)=>({type:"product" as const,key}))})),...company.documents.map((d:any)=>({externalId:d.externalId,sourceFile:`knowledge/company/${d.sourceFile}`,sourceType:d.sourceType,language:d.language,title:d.title,entities:[{type:"company" as const,key:"cudy-technology",name:"Cudy Technology"}]})),...industry.documents.map((d:any)=>({externalId:d.externalId,sourceFile:`knowledge/industry/${d.sourceFile}`,sourceType:d.sourceType,language:d.language,title:d.title,entities:[{type:"industry-topic" as const,key:d.topic,name:d.title}]}))];
let registered=0;const missing:string[]=[];for(const entry of entries){if(!await stat(resolve(entry.sourceFile)).then(v=>v.isFile()).catch(()=>false)){missing.push(entry.sourceFile);continue;}const docs=await tenantQuery<{id:string}>(OWNER_USER_ID,"select id from knowledge_document where owner_id=$1 and external_id=$2",[OWNER_USER_ID,entry.externalId],"admin");if(!docs[0]){missing.push(`document:${entry.externalId}`);continue;}await registerKnowledgeAsset(OWNER_USER_ID,{documentId:docs[0].id,storageKey:entry.sourceFile,documentType:entry.sourceFile.split(".").pop()?.toUpperCase()??"FILE",version:entry.version,language:entry.language,sourceNature:entry.sourceType,externallyDisclosable:entry.sourceType.startsWith("public-")});await linkKnowledgeDocumentEntities(OWNER_USER_ID,docs[0].id,entry.entities);registered++;}
async function sourceFiles(root:string){const output:string[]=[];for(const item of await readdir(root,{withFileTypes:true})){if(item.name==="processed")continue;const path=resolve(root,item.name);if(item.isDirectory())output.push(...await sourceFiles(path));else output.push(relative(process.cwd(),path).replaceAll("\\","/"));}return output;}
const discovered=[...await sourceFiles(resolve("knowledge/company")),...await sourceFiles(resolve("knowledge/industry"))];const registeredKeys=new Set(entries.map(e=>e.sourceFile.replaceAll("\\","/")));const documentTypes=entries.reduce<Record<string,number>>((sum,e)=>{const type=e.sourceFile.split(".").pop()?.toUpperCase()??"FILE";sum[type]=(sum[type]??0)+1;return sum;},{});console.log(JSON.stringify({mode:"metadata-only",registered,documentTypes,missing,unregisteredSourceFiles:discovered.filter(file=>!registeredKeys.has(file)),embeddingCalls:0,externalCalls:0},null,2));await getPool().end();
