import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import nextEnv from "@next/env";
import { Pool } from "pg";
import { databaseConnectionString, databaseSslConfiguration } from "../src/lib/rag/database-ssl";
import { getPool, tenantQuery } from "../src/lib/rag/db";
import { enqueueRun, getRun, beginCall, completeCall, readEvents, boundary, controlRun } from "../src/lib/assistant/main/repository";
import { result, type ExecutionContext } from "../src/lib/assistant/main/contracts";
import { defaultModelConfig } from "../src/lib/assistant/main/product";
import { requestApproval, decideApproval, listApprovals,decideMailBatch } from "../src/lib/assistant/main/approvals";
import { executeRegisteredTool } from "../src/lib/assistant/main/tool-execution";
import { executeMailBatch,mailBatchSchema } from "../src/lib/assistant/main/mail-tools";
import { productTools } from "../src/lib/assistant/main/tools";
import { importSkill, listSkills, readSkill, changeSkill } from "../src/lib/assistant/main/skills";
import { saveMemory, loadMemory, undoMemory } from "../src/lib/assistant/main/memory";
import { loadDecisionMemory, searchHistoricalMemory } from "../src/lib/assistant/main/memory-context";
import {listAgentMemory,setAgentMemoryActive} from "../src/lib/assistant/main/memory-management";
import {changeMemory,listMemories} from "../src/lib/outreach/memory-management";
import { createSchedule, listSchedules, changeSchedule, dispatchDueSchedule } from "../src/lib/assistant/main/schedules";
import { queueReviewedMail } from "../src/lib/assistant/main/reviewed-mail";
import {encryptMailboxContent} from "../src/lib/mailbox/crypto";
import {readTaskDetail} from "../src/lib/assistant/task-detail";
import {taskFeedSql} from "../src/lib/assistant/task-feed";

nextEnv.loadEnvConfig(process.cwd());
const url = process.env.DATABASE_MIGRATION_URL || process.env.DATABASE_URL;
if (!url) throw new Error("Database configuration required");
if (process.env.DATABASE_URL) {
  const a = new URL(url), b = new URL(process.env.DATABASE_URL);
  assert.equal(`${a.hostname}:${a.port || "5432"}${a.pathname}`, `${b.hostname}:${b.port || "5432"}${b.pathname}`);
}
const admin = new Pool({ connectionString: databaseConnectionString(url), ssl: databaseSslConfiguration(url) });
const owners = [randomUUID(), randomUUID()];
const historicalPolicyId=randomUUID();
let checks = 0;
try {
  if (process.argv.includes("--apply")) for (const migration of ["090_main_agent_runtime.sql", "091_agent_approvals.sql", "092_independent_outbound_mail.sql", "093_agent_skills.sql", "094_agent_memory.sql", "095_agent_schedules.sql", "096_agent_mail_execution.sql", "097_agent_model_batch.sql"]) await admin.query(await readFile(`db/migrations/${migration}`, "utf8"));
  for (const id of owners) await admin.query("insert into app_user(id,email,display_name) values($1,$2,'Synthetic main Agent test')", [id, `${id}@example.invalid`]);
  const input = { content: "Synthetic isolated task, no provider calls", requestKey: randomUUID(), attachments: [] };
  const run = await enqueueRun(owners[0], input, defaultModelConfig());
  assert.equal((await enqueueRun(owners[0], input, defaultModelConfig())).id, run.id); checks++;
  await assert.rejects(enqueueRun(owners[0], { ...input, content: "changed" }, defaultModelConfig())); checks++;
  assert.equal(await getRun(owners[1], run.id), null); checks++;
  await assert.rejects(enqueueRun(owners[1], { ...input, conversationId: run.conversation_id }, defaultModelConfig())); checks++;
  const context: ExecutionContext = { userId: owners[0], runId: run.id, leaseToken: randomUUID(), role: "member" };
  await tenantQuery(owners[0], "update agent_run set status='running',lease_token=$3,lease_until=now()+interval '90 seconds' where user_id=$1 and id=$2", [owners[0], run.id, context.leaseToken]);
  assert.equal((await boundary(context)).id, run.id); checks++;
  await assert.rejects(boundary({ ...context, leaseToken: randomUUID() })); checks++;
  const args = { key: "tool:one", tool: "company_read", version: "1", input: { candidateId: "synthetic" }, effect: "read" };
  const started = await beginCall(context, args); assert.equal(started.fresh, true); checks++;
  assert.equal((await beginCall(context, args)).fresh, false); checks++;
  await assert.rejects(beginCall(context, { ...args, input: { candidateId: "changed" } })); checks++;
  await completeCall(context, started.id, result({ receipt: "synthetic" }), { inputItems: 1, validOutputItems: 1, downstreamUsedItems: null });
  assert.deepEqual((await beginCall(context, args)).output?.data, { receipt: "synthetic" }); checks++;
  const events = await readEvents(owners[0], run.id, "0"); assert.equal(events.length, 1); checks++;
  assert.equal((await readEvents(owners[0], run.id, events[0].id)).length, 0); checks++;
  assert.equal((await readEvents(owners[1], run.id, "0")).length, 0); checks++;
  const sendTool = productTools.find(t => t.id === "mail_send")!;
  const mail = { to: "synthetic@example.invalid", body: "Reviewed final body" };
  const approval = await requestApproval(context, sendTool, mail);
  assert.equal((await listApprovals(owners[1], run.id)).length, 0); checks++;
  assert.equal(await decideApproval(owners[1], approval.id, approval.parameter_hash, "approve"), false); checks++;
  assert.equal(await decideApproval(owners[0], approval.id, "0".repeat(64), "approve"), false); checks++;
  const sendCall = { key: "smtp-one", tool: sendTool.id, version: sendTool.version, input: mail, effect: "send", approvalId: approval.id };
  await assert.rejects(beginCall(context, sendCall)); checks++;
  assert.equal(await decideApproval(owners[0], approval.id, approval.parameter_hash, "approve"), true); checks++;
  await assert.rejects(beginCall(context, { ...sendCall, input: { ...mail, body: "Tampered" } })); checks++;
  const authorized = await beginCall(context, sendCall); assert(authorized.fresh); checks++;
  assert.equal((await beginCall(context, { ...sendCall, key: "smtp-repeat" })).fresh,false); checks++;
  const second = await requestApproval(context, sendTool, { ...mail, to: "second@example.invalid" });
  await decideApproval(owners[0], second.id, second.parameter_hash, "approve");
  await decideApproval(owners[0], second.id, second.parameter_hash, "revoke");
  await assert.rejects(beginCall(context, { ...sendCall, key: "smtp-revoked", input: { ...mail, to: "second@example.invalid" }, approvalId: second.id })); checks++;
  const batchInput=[{...mail,to:"batch-a@example.invalid"},{...mail,to:"batch-b@example.invalid"}];
  const batch=await Promise.all(batchInput.map(item=>requestApproval(context,sendTool,item)));
  const decisions=batch.map(a=>({id:a.id,parameterHash:a.parameter_hash}));
  assert.equal(await decideMailBatch(owners[1],decisions),false);checks++;
  assert.equal(await decideMailBatch(owners[0],[decisions[0],{...decisions[1],parameterHash:"0".repeat(64)}]),false);checks++;
  assert((await listApprovals(owners[0],run.id)).filter(a=>batch.some(b=>b.id===a.id)).every(a=>a.status==="pending"));checks++;
  assert.equal(await decideMailBatch(owners[0],decisions),true);checks++;
  const edited=await requestApproval(context,sendTool,{...batchInput[0],body:"Edited final content"});
  assert.equal(edited.status,"pending");assert.notEqual(edited.id,batch[0].id);checks++;
  assert.equal((await listApprovals(owners[0],run.id)).find(a=>a.id===batch[1].id)?.status,"approved");checks++;
  let syntheticSends=0;
  const simulatedTool={...sendTool,execute:async()=>{syntheticSends++;return result({synthetic:true});}};
  const sent=await executeRegisteredTool(simulatedTool,batchInput[1],"batch-call-one",context);
  const reused=await executeRegisteredTool(simulatedTool,batchInput[1],"batch-call-two",context);
  assert.equal(syntheticSends,1);assert.equal(reused.callId,sent.callId);checks++;
  const exactBatch=mailBatchSchema.parse({batchId:"editable-batch",items:[
    {itemId:"a",connectionId:randomUUID(),to:"edit-a@example.invalid",subject:"Reviewed A",body:"Final A"},
    {itemId:"b",connectionId:randomUUID(),to:"edit-b@example.invalid",subject:"Reviewed B",body:"Final B"},
  ]});
  const parent=await beginCall(context,{key:"batch-original",tool:"mail_batch_send",version:"1",input:exactBatch,effect:"read"});
  assert.equal((await executeMailBatch(exactBatch,{...context,callId:parent.id})).status,"waiting_approval");checks++;
  const originalItems=(await listApprovals(owners[0],run.id)).filter(a=>(a.payload as {to?:string}).to?.startsWith("edit-"));
  assert.equal(await decideMailBatch(owners[0],originalItems.map(a=>({id:a.id,parameterHash:a.parameter_hash}))),true);checks++;
  const changedBatch={...exactBatch,items:[{...exactBatch.items[0],body:"New reviewed A"},exactBatch.items[1]]};
  const changedParent=await beginCall(context,{key:"batch-changed",tool:"mail_batch_send",version:"1",input:changedBatch,effect:"read"});
  assert.equal((await executeMailBatch(changedBatch,{...context,callId:changedParent.id})).status,"waiting_approval");checks++;
  const revisedItems=await listApprovals(owners[0],run.id);
  assert.equal(revisedItems.find(a=>a.id===originalItems.find(a=>(a.payload as {to:string}).to==="edit-a@example.invalid")?.id)?.status,"revoked");checks++;
  assert.equal(revisedItems.find(a=>a.id===originalItems.find(a=>(a.payload as {to:string}).to==="edit-b@example.invalid")?.id)?.status,"approved");checks++;
  const beforeInstructions={...context,instructionIds:[]};
  await controlRun(owners[0],run.id,"instruct","Stop remaining synthetic sends");
  const unstarted=await requestApproval(context,sendTool,{...mail,to:"blocked-after-instruction@example.invalid"});
  await decideApproval(owners[0],unstarted.id,unstarted.parameter_hash,"approve");
  await assert.rejects(beginCall(beforeInstructions,{...sendCall,key:"new-instruction-boundary",input:{...mail,to:"blocked-after-instruction@example.invalid"},approvalId:unstarted.id}),/New instructions/);checks++;
  assert.equal((await listApprovals(owners[0],run.id)).find(a=>a.id===unstarted.id)?.status,"approved");checks++;
  await assert.rejects(executeRegisteredTool(simulatedTool,{...mail,to:"blocked-after-instruction@example.invalid"},"instruction-leaf",beforeInstructions),/New instructions/);checks++;
  assert.equal(syntheticSends,1);checks++;
  const privateSkill = await importSkill(context, { name: "Private synthetic", source: "synthetic", files: { "SKILL.md": "Account method" }, dependencies: [] });
  assert(!(await listSkills(owners[1])).some(s => s.id === privateSkill.id)); checks++;
  const globalContext = { ...context, role: "admin" as const };
  const shared = await importSkill(globalContext, { name: "Global synthetic", source: "synthetic", files: { "SKILL.md": "Version one" }, dependencies: [] });
  assert(!(await listSkills(owners[1])).some(s => s.id === shared.id)); checks++;
  await changeSkill(globalContext, { id: shared.id, version: 1, operation: "publish" });
  assert((await listSkills(owners[1])).some(s => s.id === shared.id)); checks++;
  const secondRun = await enqueueRun(owners[1], { ...input, requestKey: randomUUID() }, defaultModelConfig());
  const otherContext = { ...context, userId: owners[1], runId: secondRun.id };
  assert.equal((await readSkill(otherContext, shared.id))?.version, 1); checks++;
  await importSkill(globalContext, { skillId: shared.id, expectedVersion: 1, name: "Global synthetic", source: "synthetic", files: { "SKILL.md": "Version two" }, dependencies: [] });
  assert.equal((await readSkill(otherContext, shared.id))?.version, 1); checks++;
  await assert.rejects(tenantQuery(owners[1], "insert into agent_run_skill(user_id,run_id,skill_id,version) values($1,$2,$3,1)", [owners[1], secondRun.id, privateSkill.id])); checks++;
  const preference = { key: "language", content: "English", kind: "preference" as const, scope: "account" as const, mandatory: false, markets: [], companies: [] };
  const memory = await saveMemory(context, preference, true);
  assert(!(await loadMemory(owners[1])).some(m => m.id === memory.id)); checks++;
  assert.equal(await undoMemory(owners[1], memory.id, 1), false); checks++;
  assert.equal(await undoMemory(owners[0], memory.id, 1), true); checks++;
  assert(!(await loadMemory(owners[0])).some(m => m.id === memory.id)); checks++;
  await saveMemory(context, { ...preference, content: "Chinese", expectedVersion: 1 }, false);
  assert.equal((await saveMemory(context, { ...preference, expectedVersion: 2 }, true)).saved, false); checks++;
  const branch=await saveMemory(context,{...preference,key:"undo-lineage",content:"Original preference"},false);
  await saveMemory(context,{...preference,key:"undo-lineage",content:"Discarded preference",markets:["DE"],expectedVersion:1},false);
  assert.equal(await undoMemory(owners[0],branch.id,2),true);checks++;
  const third=await saveMemory(context,{...preference,key:"undo-lineage",content:"Replacement preference",markets:["FR"],expectedVersion:1},false);
  assert.equal(third.version,3);checks++;
  assert.equal(await undoMemory(owners[0],branch.id,2),false);checks++;
  assert.equal(await undoMemory(owners[0],branch.id,3),true);checks++;
  const restored=(await loadMemory(owners[0])).find(m=>m.id===branch.id)!;
  assert.equal(restored.content,"Original preference");assert.equal(restored.current_version,1);assert.deepEqual(restored.market_codes,[]);checks++;
  assert.equal((await tenantQuery<{count:string}>(owners[0],"select count(*)::text count from agent_memory_version where memory_id=$1",[branch.id]))[0].count,"3");checks++;
  assert.equal(await undoMemory(owners[0],branch.id,1),true);checks++;
  await saveMemory(context,{...preference,key:"undo-lineage",content:"Reactivated preference",expectedVersion:1},false);
  assert.equal(await undoMemory(owners[0],branch.id,4),true);checks++;
  assert(!(await loadMemory(owners[0])).some(m=>m.id===branch.id));checks++;
  assert.equal(await undoMemory(owners[0],branch.id,1),false);checks++;
  const policy = await saveMemory(globalContext, { ...preference, key: "market-policy", content: "Synthetic mandatory rule", kind: "policy", scope: "global", mandatory: true, markets: ["DE"] }, false);
  assert((await loadMemory(owners[1], { market: "DE" })).some(m => m.id === policy.id)); checks++;
  assert(!(await loadMemory(owners[1], { market: "FR" })).some(m => m.id === policy.id)); checks++;
  await assert.rejects(saveMemory(context, { ...preference, kind: "policy" }, true)); checks++;
  const activeMemory=(await listAgentMemory(owners[0],0)).find(m=>m.id===memory.id)!;
  assert(activeMemory?.active);checks++;
  assert(!(await listAgentMemory(owners[1],0)).some(m=>m.id===memory.id));checks++;
  assert.equal(await setAgentMemoryActive({...context,userId:owners[1]},{id:memory.id,version:activeMemory.current_version,expectedUpdatedAt:activeMemory.updatedAt,active:false}),"not-found");checks++;
  assert.equal(await setAgentMemoryActive(context,{id:memory.id,version:activeMemory.current_version,expectedUpdatedAt:"stale",active:false}),"conflict");checks++;
  assert.equal(await setAgentMemoryActive(context,{id:memory.id,version:activeMemory.current_version,expectedUpdatedAt:activeMemory.updatedAt,active:false}),"updated");checks++;
  assert(!(await loadMemory(owners[0])).some(m=>m.id===memory.id));checks++;
  assert.equal(await setAgentMemoryActive(context,{id:memory.id,version:activeMemory.current_version,expectedUpdatedAt:activeMemory.updatedAt,active:true}),"conflict");checks++;
  const inactiveMemory=(await listAgentMemory(owners[0],0)).find(m=>m.id===memory.id)!;
  assert.equal(await setAgentMemoryActive(context,{id:memory.id,version:inactiveMemory.current_version,expectedUpdatedAt:inactiveMemory.updatedAt,active:true}),"updated");checks++;
  assert((await loadMemory(owners[0])).some(m=>m.id===memory.id));checks++;
  const globalMemory=(await listAgentMemory(owners[0],0)).find(m=>m.id===policy.id)!;
  assert.equal(await setAgentMemoryActive(context,{id:policy.id,version:globalMemory.current_version,expectedUpdatedAt:globalMemory.updatedAt,active:false}),"forbidden");checks++;
  assert.equal(await setAgentMemoryActive(globalContext,{id:policy.id,version:globalMemory.current_version,expectedUpdatedAt:globalMemory.updatedAt,active:false}),"forbidden");checks++;
  assert.equal(await setAgentMemoryActive(globalContext,{id:policy.id,version:globalMemory.current_version,expectedUpdatedAt:globalMemory.updatedAt,active:false},"global"),"updated");checks++;
  assert(!(await loadMemory(owners[1],{market:"DE"})).some(m=>m.id===policy.id));checks++;
  const accountPolicy=await saveMemory(context,{...preference,key:"account-policy",kind:"policy",content:"Synthetic account policy"},false);
  const accountPolicyRow=(await listAgentMemory(owners[0],0)).find(m=>m.id===accountPolicy.id)!;
  const policyAction={id:accountPolicy.id,version:accountPolicyRow.current_version,expectedUpdatedAt:accountPolicyRow.updatedAt,active:false};
  assert.equal(await setAgentMemoryActive(context,policyAction),"forbidden");checks++;
  assert.equal(await setAgentMemoryActive(context,policyAction,"decision"),"updated");checks++;
  const historyId=randomUUID();
  await tenantQuery(owners[0],`insert into user_outreach_memory(id,user_id,kind,external_id,title,content,market_codes,channel_roles,context)
    values($1::uuid,$2,'email-style',$1::text,'Synthetic literal %_ preference','Synthetic historical style',array['UK'],array['distributor'],$3::jsonb)`,
    [historyId,owners[0],JSON.stringify({companyExternalId:'synthetic-company',sourceMessage:'synthetic-source'})]);
  const search=(userId:string,extra:Record<string,unknown>={})=>searchHistoricalMemory(userId,{query:'%_',offset:0,limit:20,...extra});
  const history=await search(owners[0],{market:'GB',company:'synthetic-company',role:'distributor'});
  assert(history.items.some(m=>m.id===historyId));checks++;
  const original=history.items.find(m=>m.id===historyId)!;
  assert.equal(original.source_store,'user_outreach_memory');assert.equal(original.usage_scope,'internal-learning');assert.equal(original.mandatory,false);checks++;
  assert.equal((original.source_refs as {sourceMessage:string}).sourceMessage,'synthetic-source');checks++;
  assert(!(await search(owners[1])).items.some(m=>m.id===historyId));checks++;
  assert(!(await search(owners[0],{market:'FR'})).items.some(m=>m.id===historyId));checks++;
  assert(!(await search(owners[0],{company:'other-company'})).items.some(m=>m.id===historyId));checks++;
  assert(!(await search(owners[0],{role:'retailer'})).items.some(m=>m.id===historyId));checks++;
  await tenantQuery(owners[0],"update user_outreach_memory set status='archived' where id=$1",[historyId]);
  assert(!(await search(owners[0])).items.some(m=>m.id===historyId));checks++;
  const oldRevision=(await listMemories(owners[0],0)).find(m=>m.id===historyId)!.updatedAt;
  assert.equal(await changeMemory(owners[1],{id:historyId,operation:"delete",confirmed:true,expectedUpdatedAt:oldRevision}),"not-found");checks++;
  assert.equal(await changeMemory(owners[0],{id:historyId,operation:"activate",confirmed:true,expectedUpdatedAt:"stale"}),"conflict");checks++;
  assert.equal(await changeMemory(owners[0],{id:historyId,operation:"activate",confirmed:true,expectedUpdatedAt:oldRevision}),"ok");checks++;
  assert((await search(owners[0])).items.some(m=>m.id===historyId));checks++;
  assert.equal(await changeMemory(owners[0],{id:historyId,operation:"delete",confirmed:true,expectedUpdatedAt:oldRevision}),"conflict");checks++;
  const newRevision=(await listMemories(owners[0],0)).find(m=>m.id===historyId)!.updatedAt;
  assert.equal(await changeMemory(owners[0],{id:historyId,operation:"delete",confirmed:true,expectedUpdatedAt:newRevision}),"ok");checks++;
  assert(!(await search(owners[0])).items.some(m=>m.id===historyId));checks++;
  await admin.query(`insert into outreach_knowledge_item(id,visibility,kind,external_id,title,content,market_codes,source_refs,approval_status)
    values($1::uuid,'shared','distribution-policy',$1::text,'Synthetic policy','Synthetic default policy',array['BENELUX'],$2::jsonb,'active')`,
    [historicalPolicyId,JSON.stringify({companyExternalId:'synthetic-company'})]);
  const inherited=(await loadDecisionMemory(owners[1],{market:'NL',company:'synthetic-company'})).find(m=>m.id===historicalPolicyId)!;
  assert(inherited);assert.equal(inherited.mandatory,false);assert.equal(inherited.source_kind,'legacy-active');checks++;
  assert(!(await loadDecisionMemory(owners[1],{market:'DE'})).some(m=>m.id===historicalPolicyId));checks++;
  assert(!(await loadDecisionMemory(owners[1],{market:'NL',company:'other-company'})).some(m=>m.id===historicalPolicyId));checks++;
  await admin.query("update outreach_knowledge_item set content='Revised synthetic default',updated_at=now() where id=$1",[historicalPolicyId]);
  const revised=(await loadDecisionMemory(owners[1],{market:'NL',company:'synthetic-company'})).find(m=>m.id===historicalPolicyId)!;
  assert.notEqual(JSON.stringify(revised),JSON.stringify(inherited));checks++;
  await admin.query("update outreach_knowledge_item set approval_status='archived' where id=$1",[historicalPolicyId]);
  assert(!(await loadDecisionMemory(owners[1])).some(m=>m.id===historicalPolicyId));checks++;
  const schedule = await createSchedule(owners[0], { title: "Synthetic schedule", content: "Synthetic task with no provider calls", plan: { kind: "interval", minutes: 60 } });
  assert.equal(schedule.timezone, "Asia/Shanghai"); checks++;
  assert(!(await listSchedules(owners[1])).some(s => s.id === schedule.id)); checks++;
  assert.equal(await changeSchedule(owners[1], schedule.id as string, 1, false), false); checks++;
  assert.equal(await changeSchedule(owners[0], schedule.id as string, 2, false), false); checks++;
  await tenantQuery(owners[0], "update agent_schedule set next_run_at=now()-interval '3 days' where id=$1 and user_id=$2", [schedule.id, owners[0]]);
  assert.equal(await dispatchDueSchedule(schedule.id as string), true); checks++;
  const scheduled = (await listSchedules(owners[0])).find(s => s.id === schedule.id)!;
  assert(scheduled.active_run_id && new Date(scheduled.next_run_at as string).getTime() > Date.now()); checks++;
  await tenantQuery(owners[0], "update agent_schedule set next_run_at=now()-interval '1 hour' where id=$1 and user_id=$2", [schedule.id, owners[0]]);
  assert.equal(await dispatchDueSchedule(schedule.id as string), false); checks++;
  await controlRun(owners[0], scheduled.active_run_id as string, "cancel");
  assert.equal(await dispatchDueSchedule(schedule.id as string), true); checks++;
  assert.notEqual((await listSchedules(owners[0])).find(s => s.id === schedule.id)?.active_run_id, scheduled.active_run_id); checks++;
  await controlRun(owners[0], run.id, "cancel");
  await assert.rejects(beginCall(context, { ...args, key: "tool:two" })); checks++;
  const tables = await admin.query<{ forced: boolean }>("select relforcerowsecurity as forced from pg_class where relname=any($1::text[])", [["agent_run", "agent_run_event", "agent_tool_call"]]);
  assert.equal(tables.rows.length, 3); assert(tables.rows.every(t => t.forced)); checks++;
  // Disabled fixture accounts cannot be claimed by any real background worker.
  // The unusable ciphertext is never decrypted and SMTP is never invoked.
  await admin.query("update app_user set status='disabled' where id=$1",[owners[0]]);
  const sender=await admin.query<{id:string}>("insert into mailbox_connection(user_id,provider,email,credential_ciphertext,smtp_verified_at) values($1,'alimail-imap','sender@example.invalid','synthetic-unusable',now()) returning id",[owners[0]]);
  const reviewed={connectionId:sender.rows[0].id,to:"human-reviewed@example.invalid",subject:"Exact human confirmation",body:"Synthetic final body",confirmed:true as const,idempotencyKey:randomUUID()};
  const queued=await queueReviewedMail(owners[0],"member",reviewed);
  assert.equal(queued.status,"queued");checks++;
  const queuedRun=await getRun(owners[0],queued.runId);
  assert.equal(queuedRun?.execution_kind,"mail");assert.equal(queuedRun?.status,"queued");checks++;
  const reviewApprovals=await listApprovals(owners[0],queued.runId);
  assert.equal(reviewApprovals.length,1);assert.equal(reviewApprovals[0].status,"approved");checks++;
  assert.equal((reviewApprovals[0].payload as {body:string}).body,reviewed.body);checks++;
  assert.equal((await queueReviewedMail(owners[0],"member",reviewed)).runId,queued.runId);checks++;
  await assert.rejects(queueReviewedMail(owners[0],"member",{...reviewed,body:"Changed after confirmation"}),/different content/);checks++;
  assert.equal((await admin.query("select id from outbound_mail where user_id=any($1::uuid[])",[owners])).rowCount,0);checks++;
  const standaloneMailId=randomUUID();
  const standaloneCipher=encryptMailboxContent(owners[0],{subject:"Synthetic standalone",bodyText:"Synthetic private mail body",sender:["sender@example.invalid"],recipients:["recipient@example.invalid"]});
  await admin.query(`insert into outbound_mail(id,user_id,connection_id,idempotency_key,request_hash,message_id,content_ciphertext,status)
    values($1::uuid,$2,$3,$1::uuid,'synthetic-standalone-receipt',$1::uuid::text,$4,'unknown')`,[standaloneMailId,owners[0],sender.rows[0].id,standaloneCipher]);
  const ownedMail=await readTaskDetail(owners[0],standaloneMailId,"send");
  assert.equal((ownedMail?.details as {company:string|null}).company,null);checks++;
  assert.equal((ownedMail?.details as {bodyText:string}).bodyText,"Synthetic private mail body");checks++;
  assert.equal(await readTaskDetail(owners[1],standaloneMailId,"send"),null);checks++;
  const ownedFeed=await tenantQuery<{id:string;title:string}>(owners[0],taskFeedSql,[owners[0],"all","all","all",0]);
  assert(ownedFeed.some(item=>item.id===standaloneMailId&&item.title.includes("自定义邮件")));checks++;
  const otherFeed=await tenantQuery<{id:string}>(owners[1],taskFeedSql,[owners[1],"all","all","all",0]);
  assert(!otherFeed.some(item=>item.id===standaloneMailId));checks++;
  console.log(JSON.stringify({ passed: checks, synthetic: true, modelCalls: 0, searchCalls: 0, sends: 0, customerDataModified: false }));
} finally {
  await admin.query("delete from outbound_mail where user_id=any($1::uuid[])",[owners]);
  await admin.query("delete from outreach_knowledge_item where id=$1",[historicalPolicyId]);
  await admin.query("delete from agent_schedule where user_id=any($1::uuid[])", [owners]);
  await admin.query("delete from agent_memory_version where memory_id in(select id from agent_memory where owner_id=any($1::uuid[]))", [owners]);
  await admin.query("delete from agent_memory where owner_id=any($1::uuid[])", [owners]);
  await admin.query("delete from agent_run_skill where user_id=any($1::uuid[])", [owners]);
  await admin.query("delete from agent_skill_version where skill_id in(select id from agent_skill where owner_id=any($1::uuid[]))", [owners]);
  await admin.query("delete from agent_skill where owner_id=any($1::uuid[])", [owners]);
  for (const id of owners) {
    // The legacy audit trigger needs its parent account alive during DELETE.
    await admin.query("delete from user_outreach_memory where user_id=$1",[id]);
    await admin.query("delete from agent_run_event where user_id=$1", [id]);
    await admin.query("delete from agent_tool_call where user_id=$1", [id]);
    await admin.query("delete from agent_approval where user_id=$1", [id]);
    await admin.query("delete from agent_run where user_id=$1", [id]);
    await admin.query("delete from assistant_message where user_id=$1", [id]);
    await admin.query("delete from assistant_conversation where user_id=$1", [id]);
    await admin.query("delete from app_user where id=$1", [id]);
  }
  await admin.end(); await getPool().end();
}
